typography_spectrum: 0.5
content_rating:
  adult: false
color:
  lightness: 0.5253658177157319
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  saturation: 0.17420944948080216
  brandStrength: 0.9317274661575741
  rhythmicContrast: 0.4988087656672133
github: true
opengraph: {}
layout_spectrum: 0.5
analytics:
  twitter: '#adventure'
author:
  name: 'Bryan '
  email: awayandabout@gmail.com
name: tourisimo
url: 'https://thegrid.ai/tourisimo'
navigation:
  - name: travel
    id: 30a63dec-9b1d-4b8b-9c97-321605e13db4
    type: content
  - name: equipment
    id: 3102692a-9266-4f44-85b7-9afa30480bb3
    type: content
  - name: about
    id: 533f97e5-e909-4afd-8151-2076c49c0c25
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6eeab174-b31e-47a9-8143-0bc73c28f38c.png
title: life’s an adventure - so live it!
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/da6c22b3-bdec-4d69-861a-bc5f9ccd6158.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/da6c22b3-bdec-4d69-861a-bc5f9ccd6158.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb0470c0-16ab-4120-b4d6-782f9278a611.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb0470c0-16ab-4120-b4d6-782f9278a611.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: travelling in the UK and Europe
