typography_spectrum: 0.5
content_rating:
  adult: false
color:
  lightness: 0.5253658177157319
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  saturation: 0.17420944948080216
  brandStrength: 0.9317274661575741
  rhythmicContrast: 0.4988087656672133
github: true
opengraph: {}
layout_spectrum: 0.5
analytics:
  twitter: '#adventure'
author:
  name: 'Bryan '
  email: awayandabout@gmail.com
name: tourisimo
navigation:
  - name: Travel
    id: 30a63dec-9b1d-4b8b-9c97-321605e13db4
    type: content
title: life’s an adventure - so live it!
content: []
description: travel around the UK and Europe
