name: tourisimo
analytics:
  twitter: '#adventure'
content_rating:
  adult: false
github: true
description: travel around the UK and Europe
opengraph: {}
title: life’s an adventure - so live it!
author:
  name: 'Bryan '
  email: awayandabout@gmail.com
color:
  lightness: 0.5253658177157319
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  saturation: 0.17420944948080216
  brandStrength: 0.9317274661575741
  rhythmicContrast: 0.4988087656672133
